TITLES=[
  ['le grand', 'la grande'],
  ['le superbe', 'la superbe'],
  ['le huttin'],
  ['le terrible', 'la terrible'],
  ['le borgne'],
  ['le beau', 'la belle'],
  ["l'ancien"],
  ['le fourbe'],
  ['le cagneux'],
  ['le vil'],
  ['le magnanime'],
  ['le formidable'],
  ["l'affreux"],
  ['le noir', 'la noire'],
  ['le blanc', 'la blanche'],
  ['le brun', 'la brune'],
  ["l'écarlate", "l'écarlate"],
  [nil, 'la bigarrée'],
  [nil, 'la purpurine'],
  ['le majestueux', 'la majestueuse'],
  [nil, 'la rayonnante'],
  [nil, 'la divine'],
  ["l'éradicateur"],
  ['le serpent', 'la vipère'],
  ['le traitre', 'la traitraisse'],
  ['le paranoïaque'],
  ['le sombre', 'la sombre'],
  ['le sanguin', 'la colérique'],
]